### ISSUE TITLE
Add decorator to allow styled-components ThemeProvider

### ISSUE THREAD

**Issue by arosenb2** [tonai/storybook-addon-themes#13]
Instead of only limiting this to a single way of implementing themes, it'd be very helpful to open it up to other solutions via custom decorators, or examples of how to interact with this via a custom decorator for things like styled-components

**Comment by tonai** [comment]
Hello, do you have an example of the expected usage you want ?

**Comment by carlitoplatanito** [comment]
I was actually looking for a similar solution. So instead of just maybe passing what classes change you can pass an object with all props that change and a way to feed it what 'ThemeProvider' component to use instead of the default decorating 'div'. For example...

```js
import { ThemeProvider } from '@material-ui/core/styles';
// ...
addParameters({
  themes: [
    { name: 'twitter', props: { theme: 'twitter' }, color: '#00aced', default: true },
    { name: 'facebook', props: { theme: 'facebook' }, color: '#3b5998' },
  ],
 themeComponent: ThemeProvider
});
```

When selected all the props will just get drilled into the passed `themeComponent`, ie (<ThemeProvider ...props />)... hope this makes sense, will be looking to possibly make a pull request or I can just fork this if you do not anticipate it ever working that way.

**Comment by tonai** [comment]
Hi @carlosl,
ok I understand the need.

The problem is that it is not so easy...
You can't put functions in the object to `addParameters` because the object get serialized and deserialized.
All functions put in that object end up being empty functions when you get them in the addon.

**Comment by vancityliam** [comment]
Hi there. I had a go at solving this and tested with my own application and it seemed to work. Let me know what you think - https://github.com/tonai/storybook-addon-themes/pull/22

example of usage in `preview.js`:
`addDecorator(withThemesCustomConfiguration(ThemeProvider));`

**Comment by tonai** [comment]
Thanks @sultrytsardine I will check that.
I've also come to some solution on my side, but it is worth comparing.

**Comment by tonai** [comment]
I've made some test and it seems that passing a function to the parameters is now functional, so we don't need some specific trick anymore.

I will make a new PR with that new option.

**Comment by tonai** [comment]
New version 5.4.0 released.
