### ISSUE TITLE
Apply a function to set theme

### ISSUE THREAD

**Issue by bennypowers** [tonai/storybook-addon-themes#28]
Hello!

This addon looks really nice, thanks for publishing it.

I'd like to be able to specify a function that's called when the addon's theme changes. Our app uses a `theme="light"` attr on the body in order to toggle theme.

So I'd like to do something like

```js
addParameters({
  themes: {
      list: [
        { name: 'light', default: true },
        { name: 'dark' },
      ],
      onChange(theme) {
        document.body.setAttribute('theme', theme.name)
      }
  }
});
```

**Comment by aaronbarker** [comment]
I came looking for something similar. Or maybe another way to get the same result would be to allow an option to set the attribute to use which would override `class`.

**Comment by brunano21** [comment]
@aaronbarker I do have the same requirements, because our components depend on a body attribute and not a class. Also, we would need to reload the iframe, since the components get the theme to apply at creation time (and not at run-time).

**Comment by tonai** [comment]
Hi and sorry for my late reply.
Even if the `onChange` option is added, it will be more difficult to do what you want since the preview is inside an iframe.
Maybe you can do what you want by using a custom decorator: https://github.com/tonai/storybook-addon-themes#custom-decorator
When using the decorator you can add an intermediate element with the attribute you need.
If using the body element a requirement for you, you can still use `useEffect` in the decorator to do what you want (the decorator is inside the iframe so you can use `document.body` here).

**Comment by tonai** [comment]
Adding the `onChange` parameter was not a big deal so I make the following PR: https://github.com/tonai/storybook-addon-themes/pull/33
But remember that the `onChange` callback executes in the context of the storybook manager and not in the iframe (the preview).

**Comment by tonai** [comment]
Version 5.5.0 just published.
Enjoy :smiley:
